name: AriTulla
favicon: null
layout_spectrum: 0.8001297251321375
typography_spectrum: 0.45238820975646377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5831983215175569
  lightness: 0.05671269982121885
  saturation: 0.4913815036416054
  rhythmicContrast: 0.5750750962179154
purpose: []
